import { ResourceCost } from '../types';

export interface CrownspireTroop {
  id: string;
  name: string;
  troopType: 'infantry' | 'marksmen' | 'cavalry';
  tier: number;
  attack: number;
  defense: number;
  health: number;
  speed: number;
  load: number;
  power: number;
  trainingCost: ResourceCost;
  trainingTimeSec: number;
  upkeep: number;
  unlockRequirement: string;
  description: string;
  iconName: string;
}

export const CROWNSPIRE_TROOPS: CrownspireTroop[] = [
  // --- INFANTRY (T1 - T12) ---
  {
    id: 'infantry_t1',
    name: 'Citadel Recruit',
    troopType: 'infantry',
    tier: 1,
    attack: 5,
    defense: 4,
    health: 50,
    speed: 10,
    load: 8,
    power: 8,
    trainingCost: { food: 60, wood: 10 },
    trainingTimeSec: 4,
    upkeep: 0.1,
    unlockRequirement: 'Infantry Barracks Lv. 1',
    description: 'Basic foot soldier armed with iron-tipped spears. Low damage, high courage.',
    iconName: 'User'
  },
  {
    id: 'infantry_t2',
    name: 'Iron Spearman',
    troopType: 'infantry',
    tier: 2,
    attack: 10,
    defense: 9,
    health: 90,
    speed: 11,
    load: 10,
    power: 15,
    trainingCost: { food: 120, wood: 20 },
    trainingTimeSec: 8,
    upkeep: 0.2,
    unlockRequirement: 'Infantry Barracks Lv. 3',
    description: 'Garrison spearmen with broad shields trained to stop light cavalry charges.',
    iconName: 'Shield'
  },
  {
    id: 'infantry_t3',
    name: 'Royal Shieldbearer',
    troopType: 'infantry',
    tier: 3,
    attack: 18,
    defense: 22,
    health: 160,
    speed: 11,
    load: 12,
    power: 30,
    trainingCost: { food: 250, wood: 50, stone: 20 },
    trainingTimeSec: 15,
    upkeep: 0.4,
    unlockRequirement: 'Infantry Barracks Lv. 6',
    description: 'Frontline vanguard clad in plate and armed with a towering iron shield.',
    iconName: 'Shield'
  },
  {
    id: 'infantry_t4',
    name: 'Valiant Swordsman',
    troopType: 'infantry',
    tier: 4,
    attack: 35,
    defense: 30,
    health: 280,
    speed: 12,
    load: 14,
    power: 60,
    trainingCost: { food: 500, wood: 120, iron: 40 },
    trainingTimeSec: 30,
    upkeep: 0.7,
    unlockRequirement: 'Infantry Barracks Lv. 10',
    description: 'Skilled shock gladiators adept at breaking enemy phalanges with dual-wielding steel.',
    iconName: 'Sword'
  },
  {
    id: 'infantry_t5',
    name: 'Guard Halberdier',
    troopType: 'infantry',
    tier: 5,
    attack: 65,
    defense: 55,
    health: 450,
    speed: 12,
    load: 16,
    power: 120,
    trainingCost: { food: 1000, wood: 250, iron: 100 },
    trainingTimeSec: 60,
    upkeep: 1.2,
    unlockRequirement: 'Infantry Barracks Lv. 14',
    description: 'Imperial long-reach polearm veterans designed to cleave mounted knights and heavy armor.',
    iconName: 'Sword'
  },
  {
    id: 'infantry_t6',
    name: 'Runeguard Sentinel',
    troopType: 'infantry',
    tier: 6,
    attack: 110,
    defense: 105,
    health: 750,
    speed: 13,
    load: 18,
    power: 250,
    trainingCost: { food: 2000, wood: 500, stone: 200, iron: 250 },
    trainingTimeSec: 120,
    upkeep: 2.0,
    unlockRequirement: 'Infantry Barracks Lv. 18',
    description: 'Fortress guardians empowered with stone runes who absorb huge punishment.',
    iconName: 'Shield'
  },
  {
    id: 'infantry_t7',
    name: 'Citadel Paladin',
    troopType: 'infantry',
    tier: 7,
    attack: 200,
    defense: 190,
    health: 1300,
    speed: 13,
    load: 20,
    power: 500,
    trainingCost: { food: 4000, wood: 1000, stone: 400, iron: 550 },
    trainingTimeSec: 240,
    upkeep: 3.5,
    unlockRequirement: 'Infantry Barracks Lv. 22',
    description: 'Sovereign guard wielding consecrated claymores to smite dark forces.',
    iconName: 'ShieldAlert'
  },
  {
    id: 'infantry_t8',
    name: 'Champion Footman',
    troopType: 'infantry',
    tier: 8,
    attack: 380,
    defense: 340,
    health: 2200,
    speed: 14,
    load: 22,
    power: 1000,
    trainingCost: { food: 8000, wood: 2000, stone: 800, iron: 1200, valor: 10 },
    trainingTimeSec: 450,
    upkeep: 6.0,
    unlockRequirement: 'Infantry Barracks Lv. 26',
    description: 'Decorated war masters carrying ancient crownmark-forged broadswords into direct siege combat.',
    iconName: 'Crown'
  },
  {
    id: 'infantry_t9',
    name: 'Obsidian Warden',
    troopType: 'infantry',
    tier: 9,
    attack: 720,
    defense: 680,
    health: 4000,
    speed: 14,
    load: 25,
    power: 2000,
    trainingCost: { food: 16000, wood: 4000, stone: 1800, iron: 2500, valor: 25 },
    trainingTimeSec: 900,
    upkeep: 10.0,
    unlockRequirement: 'Infantry Barracks Lv. 30',
    description: 'Shadow-guard commandos whose obsidian armor is impervious to arrows and light magic.',
    iconName: 'ShieldAlert'
  },
  {
    id: 'infantry_t10',
    name: 'Vanguard Juggernaut',
    troopType: 'infantry',
    tier: 10,
    attack: 1350,
    defense: 1400,
    health: 7500,
    speed: 15,
    load: 28,
    power: 4200,
    trainingCost: { food: 32000, wood: 8000, stone: 4000, iron: 6000, valor: 60 },
    trainingTimeSec: 1800,
    upkeep: 18.0,
    unlockRequirement: 'Infantry Barracks Lv. 33',
    description: 'Massive walkers clad in steel plates. Can break through castle walls singlehandedly.',
    iconName: 'Hammer'
  },
  {
    id: 'infantry_t11',
    name: 'Archon Justiciar',
    troopType: 'infantry',
    tier: 11,
    attack: 2600,
    defense: 2700,
    health: 14000,
    speed: 15,
    load: 32,
    power: 8500,
    trainingCost: { food: 65000, wood: 15000, stone: 8000, iron: 12000, valor: 150 },
    trainingTimeSec: 3600,
    upkeep: 32.0,
    unlockRequirement: 'Infantry Barracks Lv. 36',
    description: 'Legendary defenders cloaked in gold wings who punish invaders with holy celestial law.',
    iconName: 'Shield'
  },
  {
    id: 'infantry_t12',
    name: 'Eternal Godwarden',
    troopType: 'infantry',
    tier: 12,
    attack: 5200,
    defense: 5500,
    health: 28000,
    speed: 16,
    load: 40,
    power: 18000,
    trainingCost: { food: 150000, wood: 32000, stone: 16000, iron: 25000, valor: 400 },
    trainingTimeSec: 7200,
    upkeep: 60.0,
    unlockRequirement: 'Infantry Barracks Lv. 40',
    description: 'An immortal demigod of defense representing the ultimate sovereign shield of Crownspire.',
    iconName: 'Award'
  },

  // --- MARKSMEN (T1 - T12) ---
  {
    id: 'marksmen_t1',
    name: 'Novice Slinger',
    troopType: 'marksmen',
    tier: 1,
    attack: 6,
    defense: 2,
    health: 35,
    speed: 12,
    load: 6,
    power: 8,
    trainingCost: { food: 50, wood: 20 },
    trainingTimeSec: 5,
    upkeep: 0.1,
    unlockRequirement: 'Marksmen Camp Lv. 1',
    description: 'Light skirmish slingers throwing stones at short distances.',
    iconName: 'Target'
  },
  {
    id: 'marksmen_t2',
    name: 'Eldergrove Archer',
    troopType: 'marksmen',
    tier: 2,
    attack: 12,
    defense: 5,
    health: 65,
    speed: 13,
    load: 8,
    power: 18,
    trainingCost: { food: 100, wood: 45 },
    trainingTimeSec: 8,
    upkeep: 0.25,
    unlockRequirement: 'Marksmen Camp Lv. 3',
    description: 'Light archers providing crucial ranged fire using standard longbows.',
    iconName: 'Target'
  },
  {
    id: 'marksmen_t3',
    name: 'Steel Crossbowman',
    troopType: 'marksmen',
    tier: 3,
    attack: 24,
    defense: 10,
    health: 110,
    speed: 11,
    load: 10,
    power: 34,
    trainingCost: { food: 220, wood: 90, iron: 15 },
    trainingTimeSec: 16,
    upkeep: 0.45,
    unlockRequirement: 'Marksmen Camp Lv. 6',
    description: 'Armored ranged squad with hand-cranked steel bow winches. Pierces thick steel plate.',
    iconName: 'Target'
  },
  {
    id: 'marksmen_t4',
    name: 'Silver Longbowman',
    troopType: 'marksmen',
    tier: 4,
    attack: 45,
    defense: 18,
    health: 200,
    speed: 13,
    load: 12,
    power: 65,
    trainingCost: { food: 450, wood: 200, iron: 30 },
    trainingTimeSec: 32,
    upkeep: 0.8,
    unlockRequirement: 'Marksmen Camp Lv. 10',
    description: 'Elite archers shooting silverwood arrows that pierce standard armor over huge leagues.',
    iconName: 'Target'
  },
  {
    id: 'marksmen_t5',
    name: 'Shadow Skirmisher',
    troopType: 'marksmen',
    tier: 5,
    attack: 85,
    defense: 32,
    health: 340,
    speed: 14,
    load: 14,
    power: 130,
    trainingCost: { food: 900, wood: 450, iron: 80 },
    trainingTimeSec: 64,
    upkeep: 1.3,
    unlockRequirement: 'Marksmen Camp Lv. 14',
    description: 'Stealthy assassins whose poison darts weaken high value frontline leaders in seconds.',
    iconName: 'Target'
  },
  {
    id: 'marksmen_t6',
    name: 'Windrunner Pathfinder',
    troopType: 'marksmen',
    tier: 6,
    attack: 150,
    defense: 55,
    health: 550,
    speed: 15,
    load: 16,
    power: 260,
    trainingCost: { food: 1800, wood: 900, stone: 150, iron: 200 },
    trainingTimeSec: 128,
    upkeep: 2.2,
    unlockRequirement: 'Marksmen Camp Lv. 18',
    description: 'Fleet-footed arrowsmiths who double-shoot during dynamic retreat movements.',
    iconName: 'Compass'
  },
  {
    id: 'marksmen_t7',
    name: 'Heavy Arbalestier',
    troopType: 'marksmen',
    tier: 7,
    attack: 280,
    defense: 100,
    health: 950,
    speed: 11,
    load: 18,
    power: 520,
    trainingCost: { food: 3600, wood: 1800, stone: 350, iron: 450 },
    trainingTimeSec: 256,
    upkeep: 3.8,
    unlockRequirement: 'Marksmen Camp Lv. 22',
    description: 'Devastating giant arbalest artillery operators capable of pinning whole armies.',
    iconName: 'Target'
  },
  {
    id: 'marksmen_t8',
    name: 'Celestial Ranger',
    troopType: 'marksmen',
    tier: 8,
    attack: 520,
    defense: 180,
    health: 1600,
    speed: 14,
    load: 20,
    power: 1050,
    trainingCost: { food: 7200, wood: 3600, stone: 700, iron: 1000, valor: 10 },
    trainingTimeSec: 480,
    upkeep: 6.5,
    unlockRequirement: 'Marksmen Camp Lv. 26',
    description: 'Rangers wielding sun-kissed recurves who incinerate target covers with light.',
    iconName: 'Sparkles'
  },
  {
    id: 'marksmen_t9',
    name: 'Sylphward Sentry',
    troopType: 'marksmen',
    tier: 9,
    attack: 980,
    defense: 320,
    health: 2800,
    speed: 15,
    load: 22,
    power: 2100,
    trainingCost: { food: 14000, wood: 7200, stone: 1500, iron: 2000, valor: 25 },
    trainingTimeSec: 960,
    upkeep: 11.0,
    unlockRequirement: 'Marksmen Camp Lv. 30',
    description: 'Wind-spirit archers whose gale arrows alter wind currents for absolute direct accuracy.',
    iconName: 'Wind'
  },
  {
    id: 'marksmen_t10',
    name: 'Iron-Sight Gunner',
    troopType: 'marksmen',
    tier: 10,
    attack: 1850,
    defense: 600,
    health: 5000,
    speed: 12,
    load: 25,
    power: 4400,
    trainingCost: { food: 28000, wood: 14000, stone: 3200, iron: 5000, valor: 60 },
    trainingTimeSec: 1920,
    upkeep: 20.0,
    unlockRequirement: 'Marksmen Camp Lv. 33',
    description: 'Heavy dwarven matchlock gunners with telescoping scopes that split thick dragon shields.',
    iconName: 'Target'
  },
  {
    id: 'marksmen_t11',
    name: 'Storm-Volt Spellbow',
    troopType: 'marksmen',
    tier: 11,
    attack: 3500,
    defense: 1100,
    health: 9000,
    speed: 14,
    load: 28,
    power: 8800,
    trainingCost: { food: 56000, wood: 28000, stone: 6400, iron: 10000, valor: 150 },
    trainingTimeSec: 3840,
    upkeep: 35.0,
    unlockRequirement: 'Marksmen Camp Lv. 36',
    description: 'Magical archers casting thunderstorm arrows that chain lightning through dense battle ranks.',
    iconName: 'Sparkles'
  },
  {
    id: 'marksmen_t12',
    name: 'Sovereign Voidweaver',
    troopType: 'marksmen',
    tier: 12,
    attack: 7200,
    defense: 2200,
    health: 18000,
    speed: 16,
    load: 35,
    power: 19000,
    trainingCost: { food: 120000, wood: 60000, stone: 12000, iron: 20000, valor: 400 },
    trainingTimeSec: 7680,
    upkeep: 65.0,
    unlockRequirement: 'Marksmen Camp Lv. 40',
    description: 'The ultimate sniper drawing cosmic arrows from space voids, bypassing defender shields.',
    iconName: 'Award'
  },

  // --- CAVALRY (T1 - T12) ---
  {
    id: 'cavalry_t1',
    name: 'Scout Rider',
    troopType: 'cavalry',
    tier: 1,
    attack: 7,
    defense: 3,
    health: 60,
    speed: 16,
    load: 12,
    power: 10,
    trainingCost: { food: 80, wood: 10 },
    trainingTimeSec: 6,
    upkeep: 0.15,
    unlockRequirement: 'Cavalry Stable Lv. 1',
    description: 'Fast-moving cavalry designed for border patrols and map scouting.',
    iconName: 'Sword'
  },
  {
    id: 'cavalry_t2',
    name: 'Light Horseman',
    troopType: 'cavalry',
    tier: 2,
    attack: 15,
    defense: 8,
    health: 100,
    speed: 17,
    load: 15,
    power: 22,
    trainingCost: { food: 150, wood: 30 },
    trainingTimeSec: 10,
    upkeep: 0.3,
    unlockRequirement: 'Cavalry Stable Lv. 3',
    description: 'Saber-wielding horsemen who flank archers and run down routed infantry.',
    iconName: 'Sword'
  },
  {
    id: 'cavalry_t3',
    name: 'Heavy Lancer',
    troopType: 'cavalry',
    tier: 3,
    attack: 30,
    defense: 16,
    health: 180,
    speed: 15,
    load: 18,
    power: 45,
    trainingCost: { food: 300, iron: 40 },
    trainingTimeSec: 18,
    upkeep: 0.55,
    unlockRequirement: 'Cavalry Stable Lv. 6',
    description: 'Frontline lance riders with iron horse vests whose charges smash ranks.',
    iconName: 'Sword'
  },
  {
    id: 'cavalry_t4',
    name: 'Royal Knight',
    troopType: 'cavalry',
    tier: 4,
    attack: 55,
    defense: 32,
    health: 320,
    speed: 15,
    load: 20,
    power: 90,
    trainingCost: { food: 600, iron: 90 },
    trainingTimeSec: 36,
    upkeep: 1.0,
    unlockRequirement: 'Cavalry Stable Lv. 10',
    description: 'Heavy shock cavalry wielding dense swords. Excellent frontline protectors.',
    iconName: 'Shield'
  },
  {
    id: 'cavalry_t5',
    name: 'Steel Cataphract',
    troopType: 'cavalry',
    tier: 5,
    attack: 100,
    defense: 60,
    health: 550,
    speed: 14,
    load: 22,
    power: 180,
    trainingCost: { food: 1200, iron: 200 },
    trainingTimeSec: 72,
    upkeep: 1.6,
    unlockRequirement: 'Cavalry Stable Lv. 14',
    description: 'Unstoppable heavy horse wall, fully covered in scale-mail steel plates.',
    iconName: 'Shield'
  },
  {
    id: 'cavalry_t6',
    name: 'Windrunner War-rider',
    troopType: 'cavalry',
    tier: 6,
    attack: 180,
    defense: 105,
    health: 900,
    speed: 18,
    load: 25,
    power: 360,
    trainingCost: { food: 2400, wood: 300, iron: 400 },
    trainingTimeSec: 144,
    upkeep: 2.6,
    unlockRequirement: 'Cavalry Stable Lv. 18',
    description: 'Swift wild riders who strike at extreme speed and vanish.',
    iconName: 'Sword'
  },
  {
    id: 'cavalry_t7',
    name: 'Gilded Cuirassier',
    troopType: 'cavalry',
    tier: 7,
    attack: 320,
    defense: 190,
    health: 1500,
    speed: 14,
    load: 28,
    power: 720,
    trainingCost: { food: 4800, stone: 500, iron: 900 },
    trainingTimeSec: 288,
    upkeep: 4.5,
    unlockRequirement: 'Cavalry Stable Lv. 22',
    description: 'Prestige horseguards outfitted in golden armor with crushing broad-maces.',
    iconName: 'ShieldAlert'
  },
  {
    id: 'cavalry_t8',
    name: 'Dragon-Crest Dragoon',
    troopType: 'cavalry',
    tier: 8,
    attack: 600,
    defense: 350,
    health: 2600,
    speed: 16,
    load: 32,
    power: 1400,
    trainingCost: { food: 9500, stone: 1000, iron: 1800, valor: 12 },
    trainingTimeSec: 540,
    upkeep: 7.5,
    unlockRequirement: 'Cavalry Stable Lv. 26',
    description: 'Pistol-drawn light cavalry whose dynamic hit-and-run volleys cause absolute confusion.',
    iconName: 'Sword'
  },
  {
    id: 'cavalry_t9',
    name: 'Eternal Paladin',
    troopType: 'cavalry',
    tier: 9,
    attack: 1100,
    defense: 640,
    health: 4500,
    speed: 15,
    load: 36,
    power: 2800,
    trainingCost: { food: 18000, stone: 2000, iron: 3500, valor: 30 },
    trainingTimeSec: 1080,
    upkeep: 12.5,
    unlockRequirement: 'Cavalry Stable Lv. 30',
    description: 'An anointed saint of war whose holy strikes protect partners and terrorize dark fiends.',
    iconName: 'Sparkles'
  },
  {
    id: 'cavalry_t10',
    name: 'Mythril War-breaker',
    troopType: 'cavalry',
    tier: 10,
    attack: 2100,
    defense: 1200,
    health: 8000,
    speed: 15,
    load: 40,
    power: 5800,
    trainingCost: { food: 36000, stone: 4000, iron: 7000, valor: 70 },
    trainingTimeSec: 2160,
    upkeep: 22.0,
    unlockRequirement: 'Cavalry Stable Lv. 33',
    description: 'Gargantuan heavily-harnessed destriers armed with steel horns to pierce phalanxes.',
    iconName: 'Hammer'
  },
  {
    id: 'cavalry_t11',
    name: 'Sovereign Star-rider',
    troopType: 'cavalry',
    tier: 11,
    attack: 4000,
    defense: 2300,
    health: 15000,
    speed: 18,
    load: 45,
    power: 11500,
    trainingCost: { food: 72000, stone: 8000, iron: 14000, valor: 180 },
    trainingTimeSec: 4320,
    upkeep: 40.0,
    unlockRequirement: 'Cavalry Stable Lv. 36',
    description: 'Astral riders traversing space rifts to drop from orbit onto helpless frontlines.',
    iconName: 'Sparkles'
  },
  {
    id: 'cavalry_t12',
    name: 'Eternal Dragon-lord',
    troopType: 'cavalry',
    tier: 12,
    attack: 8500,
    defense: 5000,
    health: 30000,
    speed: 19,
    load: 55,
    power: 25000,
    trainingCost: { food: 150000, stone: 16000, iron: 28000, valor: 500 },
    trainingTimeSec: 8640,
    upkeep: 75.0,
    unlockRequirement: 'Cavalry Stable Lv. 40',
    description: 'The ultimate war-rider mounting massive purebred dragons that breathe divine fire.',
    iconName: 'Award'
  }
];

export const TROOP_BY_ID = CROWNSPIRE_TROOPS.reduce<{ [key: string]: CrownspireTroop }>((acc, troop) => {
  acc[troop.id] = troop;
  return acc;
}, {});

export function getRequiredLevelForTier(tier: number): number {
  if (tier === 1) return 1;
  if (tier === 2) return 3;
  if (tier === 3) return 6;
  if (tier === 4) return 10;
  if (tier === 5) return 14;
  if (tier === 6) return 18;
  if (tier === 7) return 22;
  if (tier === 8) return 26;
  if (tier === 9) return 30;
  if (tier === 10) return 33;
  if (tier === 11) return 36;
  if (tier === 12) return 40;
  return 1;
}
